(uiop/package:define-package :roswell.package.use/main
                             (:nicknames :roswell.package.use)
                             (:use :roswell.package :cl) (:shadow :use)
                             (:export) (:intern))
(in-package :roswell.package.use/main)
;;don't edit above

(defun use (r)
  (if (and (first r)
           (probe-file (first r)))
      (let ((key :use)
            (package (normalize-package (load-package (first r)))))
        (cond ((null (rest r))
               (format t "~{~(~A~%~)~}" (cdr (assoc key package))))
              ((find (second r) '("-a" "add") :test 'equal)
               (let ((nick (cdr (assoc key package))))
                 (dolist (i (nthcdr 2 r))
                   (pushnew (read-from-string (format nil ":~A" i)) nick))
                 (setf (cdr (assoc key package)) nick)
                 (save-package package (first r))
                 ))
              ((find (second r) '("-d" "rm") :test 'equal)
               (let ((nick (cdr (assoc key package))))
                 (dolist (i (nthcdr 2 r))
                   (setf nick (remove (read-from-string (format nil ":~A" i)) nick)))
                 (setf (cdr (assoc key package)) nick)
                 (save-package package (first r))))))))
